### ISSUE TITLE
Feature Request: Returning why a check failed

### ISSUE THREAD

**Issue by ifrins** [3nr1c/structure#2]
First of all congrats for :ship: the first version of Structure! 

My main usecase of this library is using it to validate some arrays or object attributes. However, as it stands now Structure doesn't provide any details of which test failed and why. 

I'd love to see something like:

```php
$arrayCheck = new \Structure\ArrayS();
$arrayCheck->setFormat(array("profile" => "array");
$failed = array();
if (!$arrayCheck->check($c, $failed)) {
    var_dump($failed); //returning which fields failed
} //...
```

Which could be accomplished using $failed as an optional parameter.

Let me know what you think about that.

**Comment by 3nr1c** [comment]
I love this idea! It will be the next thing to do, after the "value sets" feature which I'm doing right now. 

To define a little more what this failure feature should do, let me ask: how would you deal with non associative arrays? I mean, for your code, the ```$failed``` var would be something like:
```php
$failed = array(
   "profile" => "array"
);
```
But in this other situation:
```php
$arrayCheck = \Structure\Structure::ArrayS("integer[]");
$incorrect = array(1, 5, "fail");
$failed = array();
if (!$arrayCheck->check($incorrect, $failed)) {
   //...
}
```
What would you do in this case?

Thanks for your comment 😄

**Comment by ifrins** [comment]
In that case I'd love to see returned the indexes of the elements that failed the check, which for the example that you've mentioned would be:

```php
$failed = array(3); 
```

One additional thing that would be nice with this feature request is not only returning which fields failed the check but also why they failed. *Kind* of the benefits you'd get with a static-typed language but applied not only to objects but also arrays, that can be heterogenous in PHP.

**Comment by 3nr1c** [comment]
I need to commit the release 0.3, but I'll keep working on this feature. I will probably be in release 0.4 😉

**Comment by 3nr1c** [comment]
Done: 28f93b1094a356eac194a0c4341cb21648681c05
